### ISSUE TITLE
may need update due to mpi wrappers in upstream netgen

### ISSUE THREAD

**Issue by francesco-ballarin** [NGSolve/ngsPETSc#33]
Upstream has changed the way MPI is wrapped
- netgen: https://github.com/NGSolve/netgen/commit/335b926f8b04501edb202191c003ea0ecc4e0ed1 
- ngsolve: https://github.com/NGSolve/ngsolve/commit/060bef459263ea984a825408e6760e9a7b8a3d9e

Running a simple notebook such as https://github.com/fem-on-colab/fem-on-colab/blob/main/ngsolve/test-ngspetsc.ipynb results in 
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-3a9ca44d9240> in <cell line: 1>()
----> 1 mesh = Mesh(unit_square.GenerateMesh(maxh=0.5).Distribute(COMM_WORLD))

RuntimeError: ng_openmpi.so: cannot open shared object file: No such file or directory
```

cc @UZerbinati: it's unclear to me whether the issue is in `ngsPETSc`, or in `netgen` itself.

**Comment by francesco-ballarin** [comment]
cc @mhochsteger just in case the issue is actually in upstream netgen, rather than ngsPETSc.

**Comment by francesco-ballarin** [comment]
While the build script itself is at https://github.com/fem-on-colab/fem-on-colab/blob/main/ngsolve/build.sh

**Comment by UZerbinati** [comment]
Hi Francesco I tried to use ngsolve with ngsPETSc in Google Colab the other day and everything worked perfectly.
Can you confirm this is still an open issue ?

**Comment by mhochsteger** [comment]
I forgot to mention it here: The CMake setting `USE_MPI_WRAPPER` is now off by default, so the build should behave like before the setting was introduced.

**Comment by francesco-ballarin** [comment]
Thanks @mhochsteger and @UZerbinati 

Closing since https://github.com/NGSolve/netgen/commit/1e7624c7f589cd08c7915a73a10da665a8cc4eec has disabled the new mpi wrappers by default. May need to re-open if the default will be set to `ON` in future.
